export { default as Main } from './Main'
export { default as CharacterInfo } from './CharacterInfo'
export { default as Comics } from './Comics'
export { default as Series } from './Series'
export { default as Events } from './Events'
